### PR TITLE
Spelling fixes

### LINKED ISSUE #60: Maybe running golangci-lint first
I see some potential security problems and typos in your codes.
For example, there is a typo in https://github.com/teslamotors/vehicle-command/blob/e1ca5088e3c55f85c7c3f251dd306181520e4afc/pkg/connector/ble/ble.go#L115, and you can see the typo recieve everywhere(reported by misspell).
And you didn't set ReadHeaderTimeout in your https://github.com/teslamotors/vehicle-command/blob/e1ca5088e3c55f85c7c3f251dd306181520e4afc/cmd/tesla-http-proxy/server.go#L63,  which can lead to Potential Slowloris Attack(reported by gosec).

### PR DESCRIPTION
**Pull request by sethterashima**
# Description

"Recieve" -> "Receive". D'oh!

The pkg/connector/ble/ble.go method had both Receive and Recieve methods. Deleting the latter is an API-breaking change, but such changes should be expected in v0.x.x according to Go semantic versioning standards.
Fixes #60 

## Type of change

Please select all options that apply to this change:

- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Documentation update

# Checklist:

Confirm you have completed the following steps:

- [x] My code follows the style of this project.
- [x] I have performed a self-review of my code.
- [x] I have made corresponding updates to the documentation.
- [ ] I have added/updated unit tests to cover my changes.

### CODE REVIEW

File: pkg/connector/ble/ble.go [hunk 1]
```diff
@@ -112,10 +112,6 @@ func (c *Connection) Send(ctx context.Context, buffer []byte) error {
 	return nil
 }
 
-func (c *Connection) Recieve() <-chan []byte {
```
Comment (sethterashima) [inline pkg/connector/ble/ble.go:115]: There is already a Receive method.

**Review by agbpatro — APPROVED** [review]
