### PR TITLE
Tesla control windows

### LINKED ISSUE #210: window_control doesn't work with HTTP Proxy
Using the HTTP Proxy with a 2021 Model 3 in North America, the `window_control` command returns a successful 200 response with no content, and it does not open or close the windows.  I have the public key installed in the vehicle and all other commands I've tried are working fine.  The problem is only with `window_control`.

[The docs](https://developer.tesla.com/docs/fleet-api?shell#window_control) are unclear whether lat/lon must be included for `vent` command or if that only applies to `open`.  It's also unclear why there is an exception for model 3.  Regardless, I've tried omitting lat/lon, seeing them to zeroes, and also setting them to valid coordinates.  The result is the same either way.

```
# curl --cacert /share/tesla/selfsigned.pem \
  --header 'Content-Type: application/json'\
  --header "Authorization: Bearer $TESLA_API_TOKEN"\
  --data '{
    "command": "vent", \
    "lat": "0", \
    "lon": "0" 
  }'   'https://c03d64a7-tesla-http-proxy/api/1/vehicles/<redacted>/command/window_control' -v
* Host c03d64a7-tesla-http-proxy:443 was resolved.
* IPv6: (none)
* IPv4: 172.30.33.4
*   Trying 172.30.33.4:443...
* Connected to c03d64a7-tesla-http-proxy (172.30.33.4) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /share/tesla/selfsigned.pem
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_CHACHA20_POLY1305_SHA256 / X25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=c03d64a7-tesla-http-proxy
*  start date: Mar  7 13:04:16 2024 GMT
*  expire date: Mar  5 13:04:16 2034 GMT
*  common name: c03d64a7-tesla-http-proxy (matched)
*  issuer: CN=c03d64a7-tesla-http-proxy
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/secp521r1 (521/256 Bits/secBits), signed using ecdsa-with-SHA256
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://c03d64a7-tesla-http-proxy/api/1/vehicles/<redacted>/command/window_control
* [HTTP/2] [1] [:method: POST]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: c03d64a7-tesla-http-proxy]
* [HTTP/2] [1] [:path: /api/1/vehicles/<redacted>/command/window_control]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
* [HTTP/2] [1] [content-type: application/json]
* [HTTP/2] [1] [authorization: Bearer <redacted>]
* [HTTP/2] [1] [content-length: 50]
> POST /api/1/vehicles/<redacted>/command/window_control HTTP/2
> Host: c03d64a7-tesla-http-proxy
> User-Agent: curl/8.5.0
> Accept: */*
> Content-Type: application/json
> Authorization: Bearer <redacted>
> Content-Length: 50
> 
< HTTP/2 200 
< content-length: 0
< date: Mon, 11 Mar 2024 08:10:08 GMT
< 
* Connection #0 to host c03d64a7-tesla-http-proxy left intact
```

### PR DESCRIPTION
**Pull request by sethterashima**
# Description

Adds window controls to http proxy and CLI.

Fixes bug where errors were not being propagated by the http proxy.

Fixes #210

## Type of change

Please select all options that apply to this change:

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update

# Checklist:

Confirm you have completed the following steps:

- [x] My code follows the style of this project.
- [x] I have performed a self-review of my code.
- [ ] I have made corresponding updates to the documentation.
- [ ] I have added/updated unit tests to cover my changes.

### CODE REVIEW

File: pkg/proxy/command.go [hunk 1]
```diff
@@ -334,6 +334,20 @@ func ExtractCommandAction(ctx context.Context, command string, params RequestPar
...
+		if err != nil {
+			return nil, err
+		}
+		switch cmd {
+		case "vent":
+			return func(v *vehicle.Vehicle) error { return v.VentWindows(ctx) }, nil
+		case "close":
+			return func(v *vehicle.Vehicle) error { return v.CloseWindows(ctx) }, nil
+		default:
+			return nil, errors.New("command must be 'vent' or 'open'")
```
Comment (aaronpkahn) [inline pkg/proxy/command.go:349]: `'vent' or 'close'`

**Review by aaronpkahn — APPROVED** [review]

**Review by agbpatro — APPROVED** [review]
