### PR TITLE
Fix carResponse struct and Content-Type header

### LINKED ISSUE #378: Flash lights command wrong response
Tesla doc:

Image

Response:

Image

Also, response content types is always text/plain, even if I send a request with Accept: application/json

### PR DESCRIPTION
**Pull request by mehrh8**
# Description

- Update carResponse struct: Change Reason field to use "reason" in JSON, keep String for backward compatibility (deprecated).
- Fix Content-Type header: Correct handling of the Content-Type header

Fixes #378

## Type of change

Please select all options that apply to this change:

- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update

# Checklist:

Confirm you have completed the following steps:

- [x] My code follows the style of this project.
- [x] I have performed a self-review of my code.
- [ ] I have made corresponding updates to the documentation.
- [ ] I have added/updated unit tests to cover my changes.

### CODE REVIEW

File: pkg/proxy/proxy.go [hunk 1]
```diff
@@ -125,9 +125,11 @@ type Response struct {
 	ErrDetails string      `json:"error_description"`
 }
 
+// TODO: Remove "String" once backward compatibility is no longer needed.
 type carResponse struct {
 	Result bool   `json:"result"`
-	Reason string `json:"string"`
+	Reason string `json:"reason"`
+	String string `json:"string"` // Deprecated: use Reason instead.
```
Comment (sethterashima) [inline pkg/proxy/proxy.go:132]: Please add an explanation for this in the commit message (I assume this is for compatibility with the non-proxied API).

Breaking changes are conventionally allowed in v0.* releases, so I'm fine doing that as long as we bump `pkg/account/version.txt` at the same time.

Comment (mehrh8) [reply pkg/proxy/proxy.go]: As I understand, the carResponse struct is only used in the proxied API, so compatibility shouldn’t be a concern if we bump the version. Is that correct? I’ve updated the changes accordingly.

**Comment by mehrh8** [comment]
@sethterashima
